server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: junjian-design-platform
  
  profiles:
    active: dev
  
  datasource:
    url: jdbc:mysql://localhost:3306/junjian_platform?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: junjian
    password: junjian123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  
  mail:
    host: smtp.qq.com
    port: 587
    username: ${MAIL_USERNAME:your-email@qq.com}
    password: ${MAIL_PASSWORD:your-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

# JWT配置
jwt:
  secret: ${JWT_SECRET:junjian-design-platform-secret-key-2024}
  expiration: 86400000 # 24小时

# 应用配置
app:
  upload:
    path: ${UPLOAD_PATH:./uploads}
  invite-code:
    designer: ${DESIGNER_INVITE_CODE:DESIGNER2024}
    owner: ${OWNER_INVITE_CODE:OWNER2024}

# 日志配置
logging:
  level:
    com.junjian: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
# 开发环境配置
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/junjian_platform?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
  data:
    redis:
      host: localhost

---
# Docker环境配置
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql:3306/junjian_platform?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
  data:
    redis:
      host: redis